spring.application.name=trimblecars


#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create

# H2 Database
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.show-sql=false
#TO PERSIST DATA
spring.datasource.url=jdbc:h2:file:./data/trimbleCarsspring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
